### ISSUE TITLE
kkFileView演示首页

### ISSUE THREAD

**Issue by gitchenjh** [kekingcn/kkFileView#114]

**Comment by gitchenjh** [comment]
## kkFileView评论切换到Gittalk了

**Comment by wanglaomo** [comment]
Aloha

**Comment by chenghao24** [comment]
666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666

**Comment by qin0306** [comment]
最新版有点不稳定，乱码~~

**Comment by gitchenjh** [comment]
> @qin0306
> 最新版有点不稳定，乱码~~

乱码主要是没装中文字体，自行装一下字体，然后重启应用就可以了

**Comment by qin0306** [comment]
> @gitchenjh
> > @qin0306
> > 最新版有点不稳定，乱码~~
> 
> 乱码主要是没装中文字体，自行装一下字体，然后重启应用就可以了

okok

**Comment by Lhanhan** [comment]
66666666666666

**Comment by ZhangXianSenzhangxiansen** [comment]
唉，IE8是个黑洞。

**Comment by niaocaixiao** [comment]
### 如果要预览文件的访问地址需要权限呢？

**Comment by klboke** [comment]
> @niaocaixiao
> ### 如果要预览文件的访问地址需要权限呢？

我们的文件都是临时有效的，访问的token和有效期等信息都携带在url参数里了

**Comment by zydisney** [comment]
有办法禁止ctrl-s保存和ctrl-p打印吗？

**Comment by liyanwei110** [comment]
ppt中的架构图展示的时候有重叠的情况，word文件中有多个图片的时候也有重叠的情况，而且位置也很偏很难看，这个有啥方法可以处理吗？

**Comment by theBigGavin** [comment]
水印打的不够啊。pdf图片另存为 就 没水印了。

**Comment by zydisney** [comment]
有可能给pdf预览里除了disabledownload=false 也添加 disableprint=false的刚能么？？不是自己开发的，不太知道从何改起..

**Comment by gitchenjh** [comment]
> @zydisney
> 有可能给pdf预览里除了disabledownload=false 也添加 disableprint=false的刚能么？？不是自己开发的，不太知道从何改起..

打印禁止不掉的，浏览器自带的功能

**Comment by nightwolf2020** [comment]
能不能再华丽点？

**Comment by wuxjNo1** [comment]
> > @zydisney
> > 有可能给pdf预览里除了disabledownload=false 也添加 disableprint=false的刚能么？？不是自己开发的，不太知道从何改起..
> 
> 打印禁止不掉的，浏览器自带的功能

使用 pdf.js , <canvas> 标签画的话,不知道能不能禁止打印

**Comment by ytzhsh** [comment]
PPT能支持动画吗

**Comment by 18137131021** [comment]
能通过什么参数添加cookies吗，访问的资源需要登录验证

**Comment by feiver** [comment]
No glyph for code 0 (CID 0000) in font FAAAAH+DejaVuSans

**Comment by linbo1993** [comment]
上传了zip之后，里面的中文Word预览会出现乱码，直接上传中文Word不会出现乱码问题

**Comment by leecloud** [comment]
Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.artofsolving.jodconverter.office.OfficeException: could not store document: 3777d383-1560-44eb-91d9-452384d6759d.html; errorCode: 2074] with root cause

com.sun.star.task.ErrorCodeIOException: 
	at com.sun.star.lib.uno.environments.remote.Job.remoteUnoRequestRaisedException(Job.java:177) ~[jurt-3.2.1.jar:na]
	at com.sun.star.lib.uno.environments.remote.Job.execute(Job.java:143) ~[jurt-3.2.1.jar:na]
	at com.sun.star.lib.uno.environments.remote.JobQueue.enter(JobQueue.java:335) ~[jurt-3.2.1.jar:na]
	at com.sun.star.lib.uno.environments.remote.JobQueue.enter(JobQueue.java:304) ~[jurt-3.2.1.jar:na]
	at com.sun.star.lib.uno.environments.remote.JavaThreadPool.enter(JavaThreadPool.java:91) ~[jurt-3.2.1.jar:na]
	at com.sun.star.lib.uno.bridges.java_remote.java_remote_bridge.sendRequest(java_remote_bridge.java:639) ~[jurt-3.2.1.jar:na]
	at com.sun.star.lib.uno.bridges.java_remote.ProxyFactory$Handler.request(ProxyFactory.java:151) ~[jurt-3.2.1.jar:na]
	at com.sun.star.lib.uno.bridges.java_remote.ProxyFactory$Handler.invoke(ProxyFactory.java:133) ~[jurt-3.2.1.jar:na]
	at com.sun.proxy.$Proxy73.storeToURL(Unknown Source) ~[na:na]
	at org.artofsolving.jodconverter.AbstractConversionTask.storeDocument(AbstractConversionTask.java:117) ~[classes/:na]
	at org.artofsolving.jodconverter.AbstractConversionTask.execute(AbstractConversionTask.java:55) ~[classes/:na]
	at org.artofsolving.jodconverter.office.PooledOfficeManager$2.run(PooledOfficeManager.java:75) ~[classes/:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_144]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) ~[na:1.8.0_144]
	at java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_144]

**Comment by slowslowslowly** [comment]
auto cad文件显示的格式有点错乱，最下面信息表格处

**Comment by leecloud** [comment]
> @slowslowslowly
> auto cad文件显示的格式有点错乱，最下面信息表格处

你的跑起来了吗？我的传路径进去报错了，在本地是可以的，但是我把路径换成http://localhost/profile/upload/2020/07/14/3777d383-1560-44eb-91d9-452384d6759d.xlsx这样就不行了

**Comment by slowslowslowly** [comment]
> @leecloud
> > @slowslowslowly
> > auto cad文件显示的格式有点错乱，最下面信息表格处
> 
> 你的跑起来了吗？我的传路径进去报错了，在本地是可以的，但是我把路径换成http://localhost/profile/upload/2020/07/14/3777d383-1560-44eb-91d9-452384d6759d.xlsx这样就不行了
> 

我的excel没问题，auto cad的文件有问题，和你的报错类似

**Comment by dyhzhengshuai** [comment]
如果要换成html格式的预览 文件该怎么修改

**Comment by s-y-h** [comment]
打开预览为什么只有数字没有报错  没有我想要预览的文件

**Comment by LLuMM** [comment]
大文件：例如一个excel10M左右文件，使用wps导出效果有上万页，使用libreoffice转换或者你们提供的其他转换有什么建议吗，我想到的方式就只有文件分块转换，但是这个分块处理及分块细粒度还得研究研究

**Comment by chrvip** [comment]
> @zydisney
> 有办法禁止ctrl-s保存和ctrl-p打印吗？

禁止了也没用，有办法禁止截屏和对着屏幕拍吗？

**Comment by 18013133801** [comment]
同名的doc文件和ppt文件预览时会混淆显示

**Comment by GitSorcerer** [comment]
挺好用的

**Comment by GitSorcerer** [comment]
在部署后，文件名称是中文有时候无法预览，但是直接源码启动的时候又没有问题。又遇到这种问题的同学吗？？？？

**Comment by Marshalqsx** [comment]
支持多少个并发的office文档预览呢，大概？

**Comment by aplaceintime** [comment]
顶

**Comment by svenchow** [comment]
顶

**Comment by jianlei** [comment]
word中带图片的表格转换报错，怎么解决

**Comment by jiangweiatgithub** [comment]
dwg用的怎么是aspose？

**Comment by zbl400** [comment]
> dwg用的怎么是aspose？

同问， 这个 aspose cad 的依赖需要授权吗？

**Comment by campper** [comment]
水印能去掉吗 或者打在页脚

**Comment by BestLiy** [comment]
123

**Comment by BestLiy** [comment]
'"><img/src=1>

**Comment by plxddyxnmd** [comment]
请问有没有删除的功能？

**Comment by WHaiboo** [comment]
777777777777777777777777777777777

**Comment by noodlesknot** [comment]
docx图表为何预览不出来

**Comment by goleden** [comment]
word转pdf格式有点问题。

**Comment by liang-zhenxiang** [comment]
预览xlx文件 为什么有时候会报错404的????

**Comment by liang-zhenxiang** [comment]
预览xlx文件 为什么有时候会报错404的?     This application has no explicit mapping for /error, so you are seeing this as a fallback.

**Comment by LiYou89** [comment]
怎么加一个加载动画呀？

**Comment by wangwennie** [comment]
水印加了中午都是乱码

**Comment by Finley-Wang** [comment]
666

**Comment by qdjianghao** [comment]
6666666测试测试

**Comment by Finley-Wang** [comment]
系统阻止该邮件发送，请稍候联系管理员重试。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: qdjianghao<mailto:notifications@github.com>
发送时间: 2020年12月9日 14:23
收件人: kekingcn/kkFileView<mailto:kkFileView@noreply.github.com>
抄送: Finley-Wang<mailto:wflh@msn.cn>; Comment<mailto:comment@noreply.github.com>
主题: Re: [kekingcn/kkFileView] kkFileView演示首页 (#114)


6666666测试测试

―

**Comment by littleearthnut** [comment]
dafasfasdfsdf

**Comment by Finley-Wang** [comment]
系统阻止该邮件发送，请稍候联系管理员重试。


发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: littleearthnut<mailto:notifications@github.com>
发送时间: 2020年12月9日 16:13
收件人: kekingcn/kkFileView<mailto:kkFileView@noreply.github.com>
抄送: Finley-Wang<mailto:wflh@msn.cn>; Comment<mailto:comment@noreply.github.com>
主题: Re: [kekingcn/kkFileView] kkFileView演示首页 (#114)


dafasfasdfsdf

―

**Comment by liang-zhenxiang** [comment]
新建的txt编码格式ANSI的话预览是乱码这个能解决吗?

**Comment by Finley-Wang** [comment]
What ？

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: liang-zhenxiang<mailto:notifications@github.com>
发送时间: 2020年12月14日 15:03
收件人: kekingcn/kkFileView<mailto:kkFileView@noreply.github.com>
抄送: Finley-Wang<mailto:wflh@msn.cn>; Comment<mailto:comment@noreply.github.com>
主题: Re: [kekingcn/kkFileView] kkFileView演示首页 (#114)


新建的txt编码格式ANSI的话预览是乱码这个能解决吗?

―

**Comment by noodlesknot** [comment]
这是本地文件,带有图表的docx文件




这是预览的效果,图表没有预览出来,消失了






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Finley-Wang"<notifications@github.com&gt;; 
发送时间: 2020年12月14日(星期一) 下午3:05
收件人: "kekingcn/kkFileView"<kkFileView@noreply.github.com&gt;; 
抄送: "面疙瘩"<804668994@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [kekingcn/kkFileView] kkFileView演示首页 (#114)





 What ？ 
 
 发送自 Windows 10 版邮件<" rel="noopener" target="_blank">https://go.microsoft.com/fwlink/?LinkId=550986&amp;gt;应用 
 
 发件人: liang-zhenxiang<mailto:notifications@github.com&gt; 
 发送时间: 2020年12月14日 15:03 
 收件人: kekingcn/kkFileView<mailto:kkFileView@noreply.github.com&gt; 
 抄送: Finley-Wang<mailto:wflh@msn.cn&gt;; Comment<mailto:comment@noreply.github.com&gt; 
 主题: Re: [kekingcn/kkFileView] kkFileView演示首页 (#114) 
 
 
 新建的txt编码格式ANSI的话预览是乱码这个能解决吗? 
 
 ―

**Comment by Finley-Wang** [comment]
We don’t seem to know each other, are you sure the email is for me?


王毅/Finley.Wang

在线途游（北京）科技有限公司
电话：15210313961<tel:15210313961>
邮箱：wangfengli@tuyoogame.com<mailto:wangfengli@tuyoogame.com>
地址：北京市朝阳区北苑路甲13号北辰泰岳大厦15层<x-apple-data-detectors://0/2>


在 2020年12月14日，18:30，noodlesknot <notifications@github.com> 写道：

﻿

这是本地文件,带有图表的docx文件




这是预览的效果,图表没有预览出来,消失了






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Finley-Wang"<notifications@github.com&gt;;
发送时间: 2020年12月14日(星期一) 下午3:05
收件人: "kekingcn/kkFileView"<kkFileView@noreply.github.com&gt;;
抄送: "面疙瘩"<804668994@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;;
主题: Re: [kekingcn/kkFileView] kkFileView演示首页 (#114)





What ？

发送自 Windows 10 版邮件<" rel="noopener" target="_blank">https://go.microsoft.com/fwlink/?LinkId=550986&amp;gt;应用

发件人: liang-zhenxiang<mailto:notifications@github.com&gt;
发送时间: 2020年12月14日 15:03
收件人: kekingcn/kkFileView<mailto:kkFileView@noreply.github.com&gt;
抄送: Finley-Wang<mailto:wflh@msn.cn&gt;; Comment<mailto:comment@noreply.github.com&gt;
主题: Re: [kekingcn/kkFileView] kkFileView演示首页 (#114)


新建的txt编码格式ANSI的话预览是乱码这个能解决吗?

―

**Comment by noodlesknot** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kekingcn/kkFileView"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月14日(星期一) 晚上7:44
收件人:&nbsp;"kekingcn/kkFileView"<kkFileView@noreply.github.com&gt;;
抄送:&nbsp;"面疙瘩"<804668994@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [kekingcn/kkFileView] kkFileView演示首页 (#114)





 We don’t seem to know each other, are you sure the email is for me? 
 
 
 王毅/Finley.Wang 
 
 在线途游（北京）科技有限公司 
 电话：15210313961<tel:15210313961&gt; 
 邮箱：wangfengli@tuyoogame.com<mailto:wangfengli@tuyoogame.com&gt; 
 地址：北京市朝阳区北苑路甲13号北辰泰岳大厦15层<x-apple-data-detectors://0/2&gt; 
 
 
 在 2020年12月14日，18:30，noodlesknot <notifications@github.com&gt; 写道： 
 
 ﻿ 
 
 这是本地文件,带有图表的docx文件 
 
 
 
 
 这是预览的效果,图表没有预览出来,消失了 
 
 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: "Finley-Wang"<notifications@github.com&amp;gt;; 
 发送时间: 2020年12月14日(星期一) 下午3:05 
 收件人: "kekingcn/kkFileView"<kkFileView@noreply.github.com&amp;gt;; 
 抄送: "面疙瘩"<804668994@qq.com&amp;gt;; "Comment"<comment@noreply.github.com&amp;gt;; 
 主题: Re: [kekingcn/kkFileView] kkFileView演示首页 (#114) 
 
 
 
 
 
 What ？ 
 
 发送自 Windows 10 版邮件<" rel="noopener" target="_blank"&gt;https://go.microsoft.com/fwlink/?LinkId=550986&amp;amp;gt;应用 
 
 发件人: liang-zhenxiang<mailto:notifications@github.com&amp;gt; 
 发送时间: 2020年12月14日 15:03 
 收件人: kekingcn/kkFileView<mailto:kkFileView@noreply.github.com&amp;gt; 
 抄送: Finley-Wang<mailto:wflh@msn.cn&amp;gt;; Comment<mailto:comment@noreply.github.com&amp;gt; 
 主题: Re: [kekingcn/kkFileView] kkFileView演示首页 (#114) 
 
 
 新建的txt编码格式ANSI的话预览是乱码这个能解决吗? 
 
 ―

**Comment by LINDEHUAN** [comment]
该文件类型(pdf)系统暂时不支持在线预览是什么意思啊？

**Comment by LINDEHUAN** [comment]
n.keking.utils.DownloadUtils -文件下载失败，url：E:\Work\DealFile\DealFile\Preview\2020-12\a902f8e6-910b-4438-948d-73c65b9319b1.pdf
这是什么情况啊

**Comment by zzzzzz7** [comment]
demo/a.doc
预览乱码

**Comment by lonebrick** [comment]
DWG 格式文件预览一直空白,在预览测试中也是同样的问题,不知道有人遇到过吗?

**Comment by chenlin1994** [comment]
如何预览多张图片

**Comment by 1932513663** [comment]
直接支持word不转pdf预览吗

**Comment by hhm-lxb** [comment]
base64Encode 这个函数方法是什么东西，有人知道吗？

**Comment by zhenghy01856** [comment]
xlsx预览效果期望差距有点大。。。

**Comment by shishiyong** [comment]
DWG 格式文件预览一直空白,在预览测试中也是同样的问题,是不是有什么限制，有谁遇到过解决了吗

**Comment by ChouJeo** [comment]
> 水印加了中文都是乱码

兄弟，你解决了没，我这也是乱码

**Comment by bbtl-by** [comment]
<script>alert('XSS Reflected')</script>

**Comment by Simon7612** [comment]
为什么文件传上去之后过几天自动就没了，还得再手动上传，就不能永久存在吗？

**Comment by klboke** [comment]
由于该 issue 已长时间无新反馈（超过 1 年），为便于维护当前问题队列，先做关闭处理。\n\n如果问题在最新版本仍可复现，请基于最新版本重新提一个新 issue，并补充：\n1) 复现步骤\n2) 版本与部署方式\n3) 关键日志/报错截图\n\n我们会优先跟进。
