### ISSUE TITLE
URL seems to be an unsupported one

### ISSUE THREAD

**Issue by Nannny** [kekingcn/kkFileView#126]
直接用8012端口上传能正常预览docx 。但是通过
var url = 'http://127.0.0.1:8080/file/test.txt'; //要预览文件的访问地址
window.open('http://127.0.0.1:8012/onlinePreview?url='+encodeURIComponent(url));
这种方式，就报错。有人遇到过吗

2020-06-11 10:07:35.187  INFO 2628 --- [nio-8012-exec-9] c.k.w.c.OnlinePreviewController          : 预览文件url：http://222.222.222.113:8081/upload/upload/reimcburse/2020-06/xxx_637274668266100000.docx，previewType：office
2020-06-11 10:07:35.687 ERROR 2628 --- [nio-8012-exec-9] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.artofsolving.jodconverter.office.OfficeException: could not load document: 7a407c82-594c-48aa-b859-2fe8fae3c1a1.docx] with root cause

com.sun.star.lang.IllegalArgumentException: URL seems to be an unsupported one.
	at com.sun.star.lib.uno.environments.remote.Job.remoteUnoRequestRaisedException(Job.java:177) ~[jurt-3.2.1.jar!/:na]
	at com.sun.star.lib.uno.environments.remote.Job.execute(Job.java:143) ~[jurt-3.2.1.jar!/:na]
	at com.sun.star.lib.uno.environments.remote.JobQueue.enter(JobQueue.java:335) ~[jurt-3.2.1.jar!/:na]
	at com.sun.star.lib.uno.environments.remote.JobQueue.enter(JobQueue.java:304) ~[jurt-3.2.1.jar!/:na]
	at com.sun.star.lib.uno.environments.remote.JavaThreadPool.enter(JavaThreadPool.java:91) ~[jurt-3.2.1.jar!/:na]
	at com.sun.star.lib.uno.bridges.java_remote.java_remote_bridge.sendRequest(java_remote_bridge.java:639) ~[jurt-3.2.1.jar!/:na]
	at com.sun.star.lib.uno.bridges.java_remote.ProxyFactory$Handler.request(ProxyFactory.java:151) ~[jurt-3.2.1.jar!/:na]
	at com.sun.star.lib.uno.bridges.java_remote.ProxyFactory$Handler.invoke(ProxyFactory.java:133) ~[jurt-3.2.1.jar!/:na]
	at com.sun.proxy.$Proxy70.loadComponentFromURL(Unknown Source) ~[na:na]
	at org.artofsolving.jodconverter.AbstractConversionTask.loadDocument(AbstractConversionTask.java:84) ~[jodconverter-core-1.0-SNAPSHOT.jar!/:na]
	at org.artofsolving.jodconverter.AbstractConversionTask.execute(AbstractConversionTask.java:53) ~[jodconverter-core-1.0-SNAPSHOT.jar!/:na]
	at org.artofsolving.jodconverter.office.PooledOfficeManager$2.run(PooledOfficeManager.java:75) ~[jodconverter-core-1.0-SNAPSHOT.jar!/:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:1.8.0_74]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[na:1.8.0_74]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:1.8.0_74]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:1.8.0_74]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_74]

**Comment by linfangrong** [comment]
Mar 16 14:50:45 multimedia-tx-009203 journal[43250]: #011at java.lang.Thread.run(Thread.java:748) [na:1.8.0_282]#015
Mar 16 14:50:45 multimedia-tx-009203 journal[43250]: Caused by: org.artofsolving.jodconverter.office.OfficeException: could not load document: 59a9bfcb-81bc-407f-94cf-61f3be3c64c5.docx#015
Mar 16 14:50:45 multimedia-tx-009203 journal[43250]: #011at org.artofsolving.jodconverter.AbstractConversionTask.loadDocument(AbstractConversionTask.java:86) ~[office-plugin-3.3.1.jar!/:na]#015
Mar 16 14:50:45 multimedia-tx-009203 journal[43250]: #011at org.artofsolving.jodconverter.AbstractConversionTask.execute(AbstractConversionTask.java:53) ~[office-plugin-3.3.1.jar!/:na]#015
Mar 16 14:50:45 multimedia-tx-009203 journal[43250]: #011at org.artofsolving.jodconverter.office.PooledOfficeManager$2.run(PooledOfficeManager.java:75) ~[office-plugin-3.3.1.jar!/:na]#015
Mar 16 14:50:45 multimedia-tx-009203 journal[43250]: #011at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_282]#015
Mar 16 14:50:45 multimedia-tx-009203 journal[43250]: #011at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_282]#015
Mar 16 14:50:45 multimedia-tx-009203 journal[43250]: #011at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_282]#015
Mar 16 14:50:45 multimedia-tx-009203 journal[43250]: #011at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_282]#015
Mar 16 14:50:45 multimedia-tx-009203 journal[43250]: #011... 1 common frames omitted#015
Mar 16 14:50:45 multimedia-tx-009203 journal[43250]: Caused by: com.sun.star.lang.IllegalArgumentException: Unsupported URL <file:///opt/kkFileView-3.3.1/file/59a9bfcb-81bc-407f-94cf-61f3be3c64c5.docx>: "type detection failed"#015
Mar 16 14:50:45 multimedia-tx-009203 journal[43250]: #011at com.sun.star.lib.uno.environments.remote.Job.remoteUnoRequestRaisedException(Job.java:177) ~[jurt-3.2.1.jar!/:na]#015
Mar 16 14:50:45 multimedia-tx-009203 journal[43250]: #011at com.sun.star.lib.uno.environments.remote.Job.execute(Job.java:143) ~[jurt-3.2.1.jar!/:na]#015
Mar 16 14:50:45 multimedia-tx-009203 journal[43250]: #011at com.sun.star.lib.uno.environments.remote.JobQueue.enter(JobQueue.java:335) ~[jurt-3.2.1.jar!/:na]#015
Mar 16 14:50:45 multimedia-tx-009203 journal[43250]: #011at com.sun.star.lib.uno.environments.remote.JobQueue.enter(JobQueue.java:304) ~[jurt-3.2.1.jar!/:na]#015
Mar 16 14:50:45 multimedia-tx-009203 journal[43250]: #011at com.sun.star.lib.uno.environments.remote.JavaThreadPool.enter(JavaThreadPool.java:91) ~[jurt-3.2.1.jar!/:na]#015
Mar 16 14:50:45 multimedia-tx-009203 journal[43250]: #011at com.sun.star.lib.uno.bridges.java_remote.java_remote_bridge.sendRequest(java_remote_bridge.java:639) ~[jurt-3.2.1.jar!/:na]#015
Mar 16 14:50:45 multimedia-tx-009203 journal[43250]: #011at com.sun.star.lib.uno.bridges.java_remote.ProxyFactory$Handler.request(ProxyFactory.java:151) ~[jurt-3.2.1.jar!/:na]#015
Mar 16 14:50:45 multimedia-tx-009203 journal[43250]: #011at com.sun.star.lib.uno.bridges.java_remote.ProxyFactory$Handler.invoke(ProxyFactory.java:133) ~[jurt-3.2.1.jar!/:na]#015

**Comment by linfangrong** [comment]
看起来应该是多个进程同时使用同一个openoffice做转码触发的。

**Comment by yyy1sss** [comment]
这个问题解决了吗

**Comment by klboke** [comment]
由于该 issue 已长时间无新反馈（超过 1 年），为便于维护当前问题队列，先做关闭处理。\n\n如果问题在最新版本仍可复现，请基于最新版本重新提一个新 issue，并补充：\n1) 复现步骤\n2) 版本与部署方式\n3) 关键日志/报错截图\n\n我们会优先跟进。
