### ISSUE TITLE
Ubuntu 18.04 启动 libreoffice 组件失败

### ISSUE THREAD

**Issue by leolird** [kekingcn/kkFileView#246]
重现步骤：
1. ps aux | grep soffice.bin | grep -v grep 查看是否有office进程，如果有就杀掉（我本地确定没有office进程了）
2. 进入kkFileView-3.5.1/bin 执行 `./startup.sh`
3. 查看日志：
```
2021-05-25 02:37:50.116  INFO 49865 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2021-05-25 02:37:50.258  INFO 49865 --- [           main] o.s.b.a.w.s.WelcomePageHandlerMapping    : Adding welcome page template: index
2021-05-25 02:37:50.281  INFO 49865 --- [           main] cn.keking.config.WebConfig               : Add resource locations: /home/xs/opt/kkFileView-3.5.1/file/
2021-05-25 02:37:50.337  WARN 49865 --- [ProcessThread-0] o.a.j.office.ManagedOfficeProcess        : office process died with exit code 81; restarting it
2021-05-25 02:37:50.351 ERROR 49865 --- [      Thread-11] cn.keking.service.OfficePluginManager    : 启动office组件失败，请检查office组件是否可用
Exception in thread "Thread-11" org.artofsolving.jodconverter.office.OfficeException: failed to start and connect
        at org.artofsolving.jodconverter.office.ManagedOfficeProcess.startAndWait(ManagedOfficeProcess.java:58)
        at org.artofsolving.jodconverter.office.PooledOfficeManager.start(PooledOfficeManager.java:96)
        at org.artofsolving.jodconverter.office.ProcessPoolOfficeManager.start(ProcessPoolOfficeManager.java:56)
        at cn.keking.service.OfficePluginManager.startOfficeManager(OfficePluginManager.java:83)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: org.artofsolving.jodconverter.office.OfficeException: could not establish connection
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at org.artofsolving.jodconverter.office.ManagedOfficeProcess.startAndWait(ManagedOfficeProcess.java:56)
        ... 4 more
Caused by: org.artofsolving.jodconverter.office.OfficeException: could not establish connection
        at org.artofsolving.jodconverter.office.ManagedOfficeProcess.doStartProcessAndConnect(ManagedOfficeProcess.java:136)
        at org.artofsolving.jodconverter.office.ManagedOfficeProcess.access$000(ManagedOfficeProcess.java:25)
        at org.artofsolving.jodconverter.office.ManagedOfficeProcess$1.run(ManagedOfficeProcess.java:52)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        ... 1 more
Caused by: java.lang.IllegalStateException: a process with acceptString 'socket,host=127.0.0.1,port=2001' is already running; pid 49933
        at org.artofsolving.jodconverter.office.OfficeProcess.start(OfficeProcess.java:61)
        at org.artofsolving.jodconverter.office.ManagedOfficeProcess$6.attempt(ManagedOfficeProcess.java:127)
        at org.artofsolving.jodconverter.office.Retryable.execute(Retryable.java:34)
        at org.artofsolving.jodconverter.office.Retryable.execute(Retryable.java:24)
        at org.artofsolving.jodconverter.office.ManagedOfficeProcess.doStartProcessAndConnect(ManagedOfficeProcess.java:134)
        ... 7 more
```
4. 再次查看office进程，并没有异常提示的49933的进程
**NOTE：用openoffice 就没有这个上述问题**

**Comment by opkcloud** [comment]
https://github.com/kekingcn/kkFileView/issues/211

**Comment by FunnyRyan** [comment]
真的受够了 就没一个解决这个问题的~~~~难道看运气 能否运行？

centos7.8 按教程排错 什么都正常 就是报 启动office错误，开个鸟的源  跟没开一样  完全查不出原因

**Comment by klboke** [comment]
由于该 issue 已长时间无新反馈（超过 1 年），为便于维护当前问题队列，先做关闭处理。\n\n如果问题在最新版本仍可复现，请基于最新版本重新提一个新 issue，并补充：\n1) 复现步骤\n2) 版本与部署方式\n3) 关键日志/报错截图\n\n我们会优先跟进。
