### ISSUE TITLE
k8s启动报ConnectException: 拒绝连接，启动成功，访问pdf与excel失败

### ISSUE THREAD

**Issue by wzjaa** [kekingcn/kkFileView#440]
2023-03-09 05:34:10.894 ERROR 1 --- [er-offprocmng-1] o.j.l.office.LocalOfficeProcessManager   : Could not start the office process.

org.jodconverter.core.office.OfficeException: An error prevents us to start a process with --accept 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ServiceManager'
	at org.jodconverter.local.office.LocalOfficeProcessManager.executeStartProcessAndConnect(LocalOfficeProcessManager.java:441) ~[jodconverter-local-4.4.5.jar!/:4.4.5]
	at org.jodconverter.local.office.LocalOfficeProcessManager.startProcessAndConnect(LocalOfficeProcessManager.java:394) ~[jodconverter-local-4.4.5.jar!/:4.4.5]
	at org.jodconverter.local.office.LocalOfficeProcessManager.lambda$start$1(LocalOfficeProcessManager.java:212) ~[jodconverter-local-4.4.5.jar!/:4.4.5]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_251]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_251]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_251]
Caused by: org.jodconverter.core.office.OfficeException: Office process died with exit code 137
	at org.jodconverter.local.office.StartProcessAndConnectRetryable.handleConnectionFailure(StartProcessAndConnectRetryable.java:253) ~[jodconverter-local-4.4.5.jar!/:4.4.5]
	at org.jodconverter.local.office.StartProcessAndConnectRetryable.attempt(StartProcessAndConnectRetryable.java:115) ~[jodconverter-local-4.4.5.jar!/:4.4.5]
	at org.jodconverter.core.office.AbstractRetryable.execute(AbstractRetryable.java:85) ~[jodconverter-core-4.4.5.jar!/:4.4.5]
	at org.jodconverter.core.office.AbstractRetryable.execute(AbstractRetryable.java:59) ~[jodconverter-core-4.4.5.jar!/:4.4.5]
	at org.jodconverter.local.office.LocalOfficeProcessManager.executeStartProcessAndConnect(LocalOfficeProcessManager.java:427) ~[jodconverter-local-4.4.5.jar!/:4.4.5]
	... 5 common frames omitted
Caused by: org.jodconverter.local.office.OfficeConnectionException: Connection failed: 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1'; java.net.ConnectException: 拒绝连接 (Connection refused)
	at org.jodconverter.local.office.OfficeConnection.connect(OfficeConnection.java:129) ~[jodconverter-local-4.4.5.jar!/:4.4.5]
	at org.jodconverter.local.office.StartProcessAndConnectRetryable.attempt(StartProcessAndConnectRetryable.java:105) ~[jodconverter-local-4.4.5.jar!/:4.4.5]
	... 8 common frames omitted
Caused by: com.sun.star.connection.NoConnectException: java.net.ConnectException: 拒绝连接 (Connection refused)
	at com.sun.star.lib.connections.socket.socketConnector.connect(socketConnector.java:144) ~[jurt-4.1.2.jar!/:na]
	at com.sun.star.comp.connections.Connector.connect(Connector.java:119) ~[jurt-4.1.2.jar!/:na]
	at org.jodconverter.local.office.OfficeConnection.createConnection(OfficeConnection.java:231) ~[jodconverter-local-4.4.5.jar!/:4.4.5]
	at org.jodconverter.local.office.OfficeConnection.connect(OfficeConnection.java:107) ~[jodconverter-local-4.4.5.jar!/:4.4.5]

**Comment by wzjaa** [comment]
这个应该是启动成功的
2023-03-09 05:33:49.495  INFO 1 --- [er-offprocmng-0] o.j.l.office.LocalOfficeProcessManager   : Starting process with --accept 'socket,host=127.0.0.1,port=2001,tcpNoDelay=1;urp;StarOffice.ServiceManager' and profileDir '/tmp/.jodconverter_socket_host-127.0.0.1_port-2001_tcpNoDelay-1'
2023-03-09 05:33:49.595  INFO 1 --- [er-offprocmng-1] o.j.l.office.LocalOfficeProcessManager   : Starting process with --accept 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ServiceManager' and profileDir '/tmp/.jodconverter_socket_host-127.0.0.1_port-2002_tcpNoDelay-1'

**Comment by RubyXun** [comment]
你好解决了吗 如何解决的

**Comment by klboke** [comment]
由于该 issue 已长时间无新反馈（超过 1 年），为便于维护当前问题队列，先做关闭处理。\n\n如果问题在最新版本仍可复现，请基于最新版本重新提一个新 issue，并补充：\n1) 复现步骤\n2) 版本与部署方式\n3) 关键日志/报错截图\n\n我们会优先跟进。
