### ISSUE TITLE
jar 包方式部署，有人需要遇到 .xls不能预览的问题吗？.xlsx预览正常

### ISSUE THREAD

**Issue by yumu7777777** [kekingcn/kkFileView#537]

**Comment by gaoxingzaq** [comment]
去看下日志 应该是office没起来

**Comment by luheng4321** [comment]
我也遇到同样的问题,4.3.0,感觉是html转换之后的

**Comment by DisguiseSmart** [comment]
![image](https://github.com/user-attachments/assets/3b6590be-2137-406f-9e9e-c4e24804df71)
即可解决

**Comment by Holinc19** [comment]
> 去看下日志 应该是office没起来

请问下这个怎么跑起来呢。现在.doc能预览，.docx不能预览；没看出来什么问题，报错如下：


```
2024-09-06 19:36:19.368  INFO 9252 --- [tp2081952435-26] c.k.w.c.OnlinePreviewController          : 预览文件url：http://localhost:8012/demo/LSY修改名称-测试00012024-07-29.docx，previewType：OFFICE
2024-09-06 19:36:19.398  INFO 9252 --- [ter-poolentry-2] o.j.local.task.LocalConversionTask       : Executing local conversion task [docx -> pdf]...
2024-09-06 19:36:19.725 ERROR 9252 --- [ter-poolentry-2] o.j.local.task.LocalConversionTask       : Local conversion failed.

java.lang.NullPointerException: Could not open document: LSY修改名称-测试00012024-07-29.docx
	at org.jodconverter.core.util.AssertUtils.notNull(AssertUtils.java:132) ~[jodconverter-core-4.4.6.jar:4.4.6]
	at org.jodconverter.local.task.AbstractLocalOfficeTask.loadDocument(AbstractLocalOfficeTask.java:210) ~[jodconverter-local-4.4.6.jar:4.4.6]
	at org.jodconverter.local.task.LocalConversionTask.execute(LocalConversionTask.java:129) ~[jodconverter-local-4.4.6.jar:4.4.6]
	at org.jodconverter.local.office.LocalOfficeManagerPoolEntry.doExecute(LocalOfficeManagerPoolEntry.java:121) [jodconverter-local-4.4.6.jar:4.4.6]
	at org.jodconverter.core.office.AbstractOfficeManagerPoolEntry.lambda$execute$0(AbstractOfficeManagerPoolEntry.java:81) [jodconverter-core-4.4.6.jar:4.4.6]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) ~[na:1.8.0_231]
	at java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:1.8.0_231]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_231]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_231]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_231]
```

**Comment by klboke** [comment]
由于该 issue 已长时间无新反馈（超过 1 年），为便于维护当前问题队列，先做关闭处理。\n\n如果问题在最新版本仍可复现，请基于最新版本重新提一个新 issue，并补充：\n1) 复现步骤\n2) 版本与部署方式\n3) 关键日志/报错截图\n\n我们会优先跟进。
