### ISSUE TITLE
dxf view exception：  class com.aspose.cad.cadexceptions.ImageSaveException

### ISSUE THREAD

**Issue by cabinhero** [kekingcn/kkFileView#562]
The version of  aspose-cad is 23.8 . It works well with IDEA at local when view dxf file, but goes wrong after deploying on server. Following is the logs:

 
  _      _      ______   _   _         __      __  _
 | |    | |    |  ____| (_) | |        \ \    / / (_)
 | | __ | | __ | |__     _  | |   ___   \ \  / /   _    ___  __      __
 | |/ / | |/ / |  __|   | | | |  / _ \   \ \/ /   | |  / _ \ \ \ /\ / /
 |   <  |   <  | |      | | | | |  __/    \  /    | | |  __/  \ V  V /
 |_|\_\ |_|\_\ |_|      |_| |_|  \___|     \/     |_|  \___|   \_/\_/

 => Spring Boot             ::  2.4.2
 => kkFileView              ::  4.4.0-beta
 => Home site               ::  https://kkview.cn
 => Github                  ::  https://github.com/kekingcn/kkFileView
 => Gitee                   ::  https://gitee.com/kekingcn/file-online-preview
 => kk opensource community ::  https://t.zsxq.com/09ZHSXbsQ

2024-05-29 17:38:28.896  INFO 18780 --- [           main] org.eclipse.jetty.util.log               : Logging initialized @5252ms to org.eclipse.jetty.util.log.Slf4jLog
2024-05-29 17:38:29.413  INFO 18780 --- [           main] o.s.b.w.e.j.JettyServletWebServerFactory : Server initialized with port: 8012
2024-05-29 17:38:29.418  INFO 18780 --- [           main] org.eclipse.jetty.server.Server          : jetty-9.4.35.v20201120; built: 2020-11-20T21:17:03.964Z; git: bdc54f03a5e0a7e280fab27f55c3c75ee8da89fb; jvm 11.0.12+8-LTS-237
2024-05-29 17:38:29.508  INFO 18780 --- [           main] o.e.j.s.h.ContextHandler.application     : Initializing Spring embedded WebApplicationContext
2024-05-29 17:38:29.508  INFO 18780 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 2921 ms
2024-05-29 17:38:29.890  INFO 18780 --- [           main] org.eclipse.jetty.server.session         : DefaultSessionIdManager workerName=node0
2024-05-29 17:38:29.890  INFO 18780 --- [           main] org.eclipse.jetty.server.session         : No SessionScavenger set, using defaults
2024-05-29 17:38:29.892  INFO 18780 --- [           main] org.eclipse.jetty.server.session         : node0 Scavenging every 600000ms
2024-05-29 17:38:29.908  INFO 18780 --- [           main] o.e.jetty.server.handler.ContextHandler  : Started o.s.b.w.e.j.JettyEmbeddedWebAppContext@53812a9b{application,/,[file:///C:/Users/Administrator/AppData/Local/Temp/3/jetty-docbase.8012.2047233712461614352/],AVAILABLE}
2024-05-29 17:38:29.909  INFO 18780 --- [           main] org.eclipse.jetty.server.Server          : Started @6269ms
2024-05-29 17:38:30.132  INFO 18780 --- [           main] cn.keking.service.FileConvertQueueTask   : 队列处理文件转换任务启动完成 
2024-05-29 17:38:30.626  INFO 18780 --- [er-offprocmng-0] o.j.local.office.OfficeDescriptor        : soffice info (from exec path): Product: OpenOffice - Version: ??? - useLongOptionNameGnuStyle: false
2024-05-29 17:38:30.626  INFO 18780 --- [er-offprocmng-1] o.j.local.office.OfficeDescriptor        : soffice info (from exec path): Product: OpenOffice - Version: ??? - useLongOptionNameGnuStyle: false
2024-05-29 17:38:31.086  INFO 18780 --- [er-offprocmng-0] o.j.l.office.LocalOfficeProcessManager   : Starting process with --accept 'socket,host=127.0.0.1,port=2001,tcpNoDelay=1;urp;StarOffice.ServiceManager' and profileDir 'C:\Users\ADMINI~1\AppData\Local\Temp\3\.jodconverter_socket_host-127.0.0.1_port-2001_tcpNoDelay-1'
2024-05-29 17:38:31.088  INFO 18780 --- [er-offprocmng-1] o.j.l.office.LocalOfficeProcessManager   : Starting process with --accept 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ServiceManager' and profileDir 'C:\Users\ADMINI~1\AppData\Local\Temp\3\.jodconverter_socket_host-127.0.0.1_port-2002_tcpNoDelay-1'
2024-05-29 17:38:32.549  INFO 18780 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2024-05-29 17:38:33.111  INFO 18780 --- [           main] cn.keking.config.WebConfig               : Add resource locations: D:\kkFileView-4.4.0-beta\file\
2024-05-29 17:38:33.469  INFO 18780 --- [er-offprocmng-1] o.j.local.office.OfficeConnection        : Connected: 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1'
2024-05-29 17:38:33.470  INFO 18780 --- [er-offprocmng-1] o.j.l.office.LocalOfficeProcessManager   : Started process; pid: 33232
2024-05-29 17:38:33.563  INFO 18780 --- [er-offprocmng-0] o.j.local.office.OfficeConnection        : Connected: 'socket,host=127.0.0.1,port=2001,tcpNoDelay=1'
2024-05-29 17:38:33.564  INFO 18780 --- [er-offprocmng-0] o.j.l.office.LocalOfficeProcessManager   : Started process; pid: 22028
2024-05-29 17:38:33.646  INFO 18780 --- [           main] o.s.s.c.ThreadPoolTaskScheduler          : Initializing ExecutorService 'taskScheduler'
2024-05-29 17:38:33.687  INFO 18780 --- [           main] o.e.j.s.h.ContextHandler.application     : Initializing Spring DispatcherServlet 'dispatcherServlet'
2024-05-29 17:38:33.688  INFO 18780 --- [           main] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2024-05-29 17:38:33.689  INFO 18780 --- [           main] o.s.web.servlet.DispatcherServlet        : Completed initialization in 1 ms
2024-05-29 17:38:33.736  INFO 18780 --- [           main] o.e.jetty.server.AbstractConnector       : Started ServerConnector@5911e990{HTTP/1.1, (http/1.1)}{0.0.0.0:8012}
2024-05-29 17:38:33.737  INFO 18780 --- [           main] o.s.b.web.embedded.jetty.JettyWebServer  : Jetty started on port(s) 8012 (http/1.1) with context path '/'
2024-05-29 17:38:33.784  INFO 18780 --- [           main] cn.keking.ServerMain                     : kkFileView 服务启动完成，耗时:8.973397946s，演示页请访问: http://127.0.0.1:8012 
2024-05-29 17:39:11.883  INFO 18780 --- [tp2043106095-18] cn.keking.web.controller.FileController  : 上传文件：D:\kkFileView-4.4.0-beta\file\demo\角色.xlsx
2024-05-29 17:39:14.140  INFO 18780 --- [tp2043106095-18] c.k.w.c.OnlinePreviewController          : 预览文件url：http://127.0.0.1:8012/demo/角色.xlsx，previewType：OFFICE
2024-05-29 17:40:51.022  INFO 18780 --- [tp2043106095-17] cn.keking.web.controller.FileController  : 上传文件：D:\kkFileView-4.4.0-beta\file\demo\文72南沙三中1砂组构造图.gxf
2024-05-29 17:40:53.253  INFO 18780 --- [tp2043106095-17] c.k.w.c.OnlinePreviewController          : 预览文件url：http://127.0.0.1:8012/demo/文72南沙三中1砂组构造图.gxf，previewType：OTHER
2024-05-29 17:42:43.970  INFO 18780 --- [tp2043106095-53] cn.keking.web.controller.FileController  : 删除文件：D:\kkFileView-4.4.0-beta\file\demo\文72南沙三中1砂组构造图.gxf
2024-05-29 17:43:05.146  INFO 18780 --- [tp2043106095-20] cn.keking.web.controller.FileController  : 上传文件：D:\kkFileView-4.4.0-beta\file\demo\文72南沙三中1砂组1小层沉积相20231030.dxf
2024-05-29 17:43:06.928  INFO 18780 --- [tp2043106095-20] c.k.w.c.OnlinePreviewController          : 预览文件url：http://127.0.0.1:8012/demo/文72南沙三中1砂组1小层沉积相20231030.dxf，previewType：CAD
2024-05-29 17:44:36.280 ERROR 18780 --- [tp2043106095-20] cn.keking.service.FileHandlerService     : CAD转换在尝试取得任务结果时出错：

java.util.concurrent.ExecutionException: class com.aspose.cad.cadexceptions.ImageSaveException: Image export failed. com/aspose/cad/internal/ow/d (wrong name: com/aspose/cad/internal/oW/d) ---> class com.aspose.cad.internal.Exceptions.InvalidOperationException: com/aspose/cad/internal/ow/d (wrong name: com/aspose/cad/internal/oW/d)
com.aspose.cad.internal.b.d.a(Unknown Source)
com.aspose.cad.Image.b(Unknown Source)
com.aspose.cad.Image.a(Unknown Source)
com.aspose.cad.r.a(Unknown Source)
com.aspose.cad.internal.eS.b.a(Unknown Source)
com.aspose.cad.internal.eS.c.a(Unknown Source)
com.aspose.cad.Image.save(Unknown Source)
cn.keking.service.FileHandlerService.lambda$cadToPdf$1(FileHandlerService.java:374)
java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
java.base/java.lang.Thread.run(Thread.java:834)
   --- End of inner exception stack trace ---
com.aspose.cad.Image.b(Unknown Source)
com.aspose.cad.Image.a(Unknown Source)
com.aspose.cad.r.a(Unknown Source)
com.aspose.cad.internal.eS.b.a(Unknown Source)
com.aspose.cad.internal.eS.c.a(Unknown Source)
com.aspose.cad.Image.save(Unknown Source)
cn.keking.service.FileHandlerService.lambda$cadToPdf$1(FileHandlerService.java:374)
java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
java.base/java.lang.Thread.run(Thread.java:834)
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:205) ~[na:na]
	at cn.keking.service.FileHandlerService.cadToPdf(FileHandlerService.java:395) ~[classes!/:na]
	at cn.keking.service.impl.CadFilePreviewImpl.filePreviewHandle(CadFilePreviewImpl.java:56) ~[classes!/:na]
	at cn.keking.web.controller.OnlinePreviewController.onlinePreview(OnlinePreviewController.java:84) ~[classes!/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197) ~[spring-web-5.3.3.jar!/:5.3.3]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141) ~[spring-web-5.3.3.jar!/:5.3.3]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106) ~[spring-webmvc-5.3.3.jar!/:5.3.3]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894) ~[spring-webmvc-5.3.3.jar!/:5.3.3]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.3.jar!/:5.3.3]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.3.jar!/:5.3.3]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1060) ~[spring-webmvc-5.3.3.jar!/:5.3.3]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:962) ~[spring-webmvc-5.3.3.jar!/:5.3.3]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.3.jar!/:5.3.3]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) ~[spring-webmvc-5.3.3.jar!/:5.3.3]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:497) ~[jakarta.servlet-api-4.0.4.jar!/:4.0.4]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.3.jar!/:5.3.3]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:584) ~[jakarta.servlet-api-4.0.4.jar!/:4.0.4]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:791) ~[jetty-servlet-9.4.35.v20201120.jar!/:9.4.35.v20201120]
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1626) ~[jetty-servlet-9.4.35.v20201120.jar!/:9.4.35.v20201120]
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:228) ~[websocket-server-9.4.35.v20201120.jar!/:9.4.35.v20201120]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.35.v20201120.jar!/:9.4.35.v20201120]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.35.v20201120.jar!/:9.4.35.v20201120]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:113) ~[spring-web-5.3.3.jar!/:5.3.3]
	at cn.keking.web.filter.SecurityFilterProxy.doFilterInternal(SecurityFilterProxy.java:28) ~[classes!/:na]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.3.jar!/:5.3.3]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.35.v20201120.jar!/:9.4.35.v20201120]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.35.v20201120.jar!/:9.4.35.v20201120]
	at cn.keking.web.filter.AttributeSetFilter.doFilter(AttributeSetFilter.java:26) ~[classes!/:na]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.35.v20201120.jar!/:9.4.35.v20201120]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.35.v20201120.jar!/:9.4.35.v20201120]
	at cn.keking.web.filter.TrustDirFilter.doFilter(TrustDirFilter.java:49) ~[classes!/:na]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.35.v20201120.jar!/:9.4.35.v20201120]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.35.v20201120.jar!/:9.4.35.v20201120]
	at cn.keking.web.filter.TrustHostFilter.doFilter(TrustHostFilter.java:49) ~[classes!/:na]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.35.v20201120.jar!/:9.4.35.v20201120]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.35.v20201120.jar!/:9.4.35.v20201120]
	at cn.keking.web.filter.UrlCheckFilter.doFilter(UrlCheckFilter.java:49) ~[classes!/:na]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.35.v20201120.jar!/:9.4.35.v20201120]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.35.v20201120.jar!/:9.4.35.v20201120]
	at cn.keking.web.filter.BaseUrlFilter.doFilter(BaseUrlFilter.java:61) ~[classes!/:na]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.35.v20201120.jar!/:9.4.35.v20201120]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.35.v20201120.jar!/:9.4.35.v20201120]
	at cn.keking.web.filter.ChinesePathFilter.doFilter(ChinesePathFilter.java:21) ~[classes!/:na]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.35.v20201120.jar!/:9.4.35.v20201120]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.35.v20201120.jar!/:9.4.35.v20201120]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.3.jar!/:5.3.3]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.3.jar!/:5.3.3]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.35.v20201120.jar!/:9.4.35.v20201120]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.35.v20201120.jar!/:9.4.35.v20201120]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.3.jar!/:5.3.3]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.3.jar!/:5.3.3]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.35.v20201120.jar!/:9.4.35.v20201120]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.35.v20201120.jar!/:9.4.35.v20201120]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.3.jar!/:5.3.3]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.3.jar!/:5.3.3]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.35.v20201120.jar!/:9.4.35.v20201120]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.35.v20201120.jar!/:9.4.35.v20201120]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548) ~[jetty-servlet-9.4.35.v20201120.jar!/:9.4.35.v20201120]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) ~[jetty-server-9.4.35.v20201120.jar!/:9.4.35.v20201120]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:602) ~[jetty-security-9.4.35.v20201120.jar!/:9.4.35.v20201120]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.35.v20201120.jar!/:9.4.35.v20201120]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235) ~[jetty-server-9.4.35.v20201120.jar!/:9.4.35.v20201120]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624) ~[jetty-server-9.4.35.v20201120.jar!/:9.4.35.v20201120]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[jetty-server-9.4.35.v20201120.jar!/:9.4.35.v20201120]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1435) ~[jetty-server-9.4.35.v20201120.jar!/:9.4.35.v20201120]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[jetty-server-9.4.35.v20201120.jar!/:9.4.35.v20201120]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501) ~[jetty-servlet-9.4.35.v20201120.jar!/:9.4.35.v20201120]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594) ~[jetty-server-9.4.35.v20201120.jar!/:9.4.35.v20201120]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[jetty-server-9.4.35.v20201120.jar!/:9.4.35.v20201120]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350) ~[jetty-server-9.4.35.v20201120.jar!/:9.4.35.v20201120]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[jetty-server-9.4.35.v20201120.jar!/:9.4.35.v20201120]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.35.v20201120.jar!/:9.4.35.v20201120]
	at org.eclipse.jetty.server.Server.handle(Server.java:516) ~[jetty-server-9.4.35.v20201120.jar!/:9.4.35.v20201120]
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388) ~[jetty-server-9.4.35.v20201120.jar!/:9.4.35.v20201120]
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633) ~[jetty-server-9.4.35.v20201120.jar!/:9.4.35.v20201120]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380) ~[jetty-server-9.4.35.v20201120.jar!/:9.4.35.v20201120]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273) ~[jetty-server-9.4.35.v20201120.jar!/:9.4.35.v20201120]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) ~[jetty-io-9.4.35.v20201120.jar!/:9.4.35.v20201120]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) ~[jetty-io-9.4.35.v20201120.jar!/:9.4.35.v20201120]
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) ~[jetty-io-9.4.35.v20201120.jar!/:9.4.35.v20201120]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336) ~[jetty-util-9.4.35.v20201120.jar!/:9.4.35.v20201120]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313) ~[jetty-util-9.4.35.v20201120.jar!/:9.4.35.v20201120]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171) ~[jetty-util-9.4.35.v20201120.jar!/:9.4.35.v20201120]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129) ~[jetty-util-9.4.35.v20201120.jar!/:9.4.35.v20201120]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375) ~[jetty-util-9.4.35.v20201120.jar!/:9.4.35.v20201120]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773) ~[jetty-util-9.4.35.v20201120.jar!/:9.4.35.v20201120]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905) ~[jetty-util-9.4.35.v20201120.jar!/:9.4.35.v20201120]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: com.aspose.cad.cadexceptions.ImageSaveException: Image export failed. com/aspose/cad/internal/ow/d (wrong name: com/aspose/cad/internal/oW/d)
	at com.aspose.cad.Image.b(Unknown Source) ~[aspose-cad-23.8.jar!/:na]
	at com.aspose.cad.Image.a(Unknown Source) ~[aspose-cad-23.8.jar!/:na]
	at com.aspose.cad.r.a(Unknown Source) ~[aspose-cad-23.8.jar!/:na]
	at com.aspose.cad.internal.eS.b.a(Unknown Source) ~[aspose-cad-23.8.jar!/:na]
	at com.aspose.cad.internal.eS.c.a(Unknown Source) ~[aspose-cad-23.8.jar!/:na]
	at com.aspose.cad.Image.save(Unknown Source) ~[aspose-cad-23.8.jar!/:na]
	at cn.keking.service.FileHandlerService.lambda$cadToPdf$1(FileHandlerService.java:374) ~[classes!/:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	... 1 common frames omitted
Caused by: com.aspose.cad.internal.Exceptions.InvalidOperationException: com/aspose/cad/internal/ow/d (wrong name: com/aspose/cad/internal/oW/d)
	at com.aspose.cad.internal.b.d.a(Unknown Source) ~[aspose-cad-23.8.jar!/:na]
	... 11 common frames omitted

**Comment by cabinhero** [comment]
It solved by replacing aspose-cad-23.8.jar with aspose-cad-23.9.jar
