### ISSUE TITLE
抱歉，该文件版本不兼容，文件版本错误。

### ISSUE THREAD

**Issue by 13673969737** [kekingcn/kkFileView#565]
![image](https://github.com/kekingcn/kkFileView/assets/74764009/efcbe127-1fa1-46fe-8775-31ccb4ef2f94)

这是什么原因啊，有些ppt能打开，有些ppt就提示这个错误，什么情况下的ppt会有这种错误啊。弄的我现在很迷茫

**Comment by gaoxingzaq** [comment]
什么版本 试试升级下LibreOffice

**Comment by QSZJAVA** [comment]
请问解决了吗 我也遇到这个问题

**Comment by 13673969737** [comment]
> 什么版本 试试升级下LibreOffice

用的是最新版，还是一样的。还有就是我用官网地址也是某些文件是不行的

**Comment by 13673969737** [comment]
> 请问解决了吗 我也遇到这个问题

没有解决，但是有一个ppt没有转成功，我看了下是因为文件里面的幻灯片被设置了隐藏，然后就在线预览失败，把隐藏关闭了就能正常预览了，但是还有其它office文档没有预览成功，目前还没发现是为啥

**Comment by QSZJAVA** [comment]
> > 请问解决了吗 我也遇到这个问题
> 
> 没有解决，但是有一个ppt没有转成功，我看了下是因为文件里面的幻灯片被设置了隐藏，然后就在线预览失败，把隐藏关闭了就能正常预览了，但是还有其它office文档没有预览成功，目前还没发现是为啥

我是有的docx能预览 有的不行 随便新建个docx都预览不了

**Comment by Holinc19** [comment]
+1，具体报错如下：

```
2024-09-06 19:36:19.368  INFO 9252 --- [tp2081952435-26] c.k.w.c.OnlinePreviewController          : 预览文件url：http://localhost:8012/demo/LSY修改名称-测试00012024-07-29.docx，previewType：OFFICE
2024-09-06 19:36:19.398  INFO 9252 --- [ter-poolentry-2] o.j.local.task.LocalConversionTask       : Executing local conversion task [docx -> pdf]...
2024-09-06 19:36:19.725 ERROR 9252 --- [ter-poolentry-2] o.j.local.task.LocalConversionTask       : Local conversion failed.

java.lang.NullPointerException: Could not open document: LSY修改名称-测试00012024-07-29.docx
	at org.jodconverter.core.util.AssertUtils.notNull(AssertUtils.java:132) ~[jodconverter-core-4.4.6.jar:4.4.6]
	at org.jodconverter.local.task.AbstractLocalOfficeTask.loadDocument(AbstractLocalOfficeTask.java:210) ~[jodconverter-local-4.4.6.jar:4.4.6]
	at org.jodconverter.local.task.LocalConversionTask.execute(LocalConversionTask.java:129) ~[jodconverter-local-4.4.6.jar:4.4.6]
	at org.jodconverter.local.office.LocalOfficeManagerPoolEntry.doExecute(LocalOfficeManagerPoolEntry.java:121) [jodconverter-local-4.4.6.jar:4.4.6]
	at org.jodconverter.core.office.AbstractOfficeManagerPoolEntry.lambda$execute$0(AbstractOfficeManagerPoolEntry.java:81) [jodconverter-core-4.4.6.jar:4.4.6]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) ~[na:1.8.0_231]
	at java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:1.8.0_231]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_231]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_231]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_231]

```

**Comment by liuzi333** [comment]
<img width="1544" height="251" alt="Image" src="https://github.com/user-attachments/assets/fdc4dc94-5fb6-4eb2-b258-e1d429d50c34" />

试了下docx文件里面有一张图片有问题，去掉图片就能正常预览了，不知道有没有帮助

**Comment by klboke** [comment]
由于该 issue 已长时间无新反馈（超过 1 年），为便于维护当前问题队列，先做关闭处理。\n\n如果问题在最新版本仍可复现，请基于最新版本重新提一个新 issue，并补充：\n1) 复现步骤\n2) 版本与部署方式\n3) 关键日志/报错截图\n\n我们会优先跟进。
