### ISSUE TITLE
请问支持dav格式吗

### ISSUE THREAD

**Issue by alanOO7** [kekingcn/kkFileView#608]
请问支持dav格式吗

**Comment by alanOO7** [comment]
您好，试过了，不支持，程序带的转码功能也播放不了，能否有机会更新下？

**Comment by alanOO7** [comment]
dav 格式的能帮忙支持下吗，转码一直失败。
      : 预览文件url：ftp://10.201.48.245/TS24204001-1000-3/2025-02-17-15-05-10_32623_F0121 基板吸盘 掉板感应器异常.dav，previewType：MEDIACONVERT
org.bytedeco.javacv.FrameGrabber$Exception: avformat_find_stream_info() error -1094995529: Could not find stream information.
	at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber.java:857)
	at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:780)
