### ISSUE TITLE
linux 部署启动报错

### ISSUE THREAD

**Issue by CrazyLittleArmy** [kekingcn/kkFileView#71]
这个该如何解决？
Caused by: java.lang.IllegalStateException: process with acceptString 'socket,host=127.0.0.1,port=8100' started but its pid could not be found
        at org.artofsolving.jodconverter.office.OfficeProcess.start(OfficeProcess.java:90) ~[jodconverter-core-1.0-SNAPSHOT.jar!/:na]
        at org.artofsolving.jodconverter.office.OfficeProcess.start(OfficeProcess.java:54) ~[jodconverter-core-1.0-SNAPSHOT.jar!/:na]
        at org.artofsolving.jodconverter.office.ManagedOfficeProcess.doStartProcessAndConnect(ManagedOfficeProcess.java:113) ~[jodconverter-core-1.0-SNAPSHOT.jar!/:na]

**Comment by Oushinan** [comment]
请参考：https://blog.csdn.net/weixin_43128854/article/details/128236271

**Comment by klboke** [comment]
由于该 issue 已长时间无新反馈（超过 1 年），为便于维护当前问题队列，先做关闭处理。\n\n如果问题在最新版本仍可复现，请基于最新版本重新提一个新 issue，并补充：\n1) 复现步骤\n2) 版本与部署方式\n3) 关键日志/报错截图\n\n我们会优先跟进。
