### ISSUE TITLE
在Windows10中启动了kkFileView-2.1.2版本，预览word报错

### ISSUE THREAD

**Issue by PlayTaoist** [kekingcn/kkFileView#86]
预览的地址是：http://127.0.0.1:8012/onlinePreview?url=http%3A%2F%2Fkelan.nat300.top%2Fprofile%2Favatar%2F2019%2F11%2F08%2F123456.doc

报如下错误，这是什么问题？？？？
com.sun.star.task.ErrorCodeIOException: 
	at com.sun.star.lib.uno.environments.remote.Job.remoteUnoRequestRaisedException(Job.java:177) ~[jurt-3.2.1.jar!/:na]
	at com.sun.star.lib.uno.environments.remote.Job.execute(Job.java:143) ~[jurt-3.2.1.jar!/:na]
	at com.sun.star.lib.uno.environments.remote.JobQueue.enter(JobQueue.java:335) ~[jurt-3.2.1.jar!/:na]
	at com.sun.star.lib.uno.environments.remote.JobQueue.enter(JobQueue.java:304) ~[jurt-3.2.1.jar!/:na]
	at com.sun.star.lib.uno.environments.remote.JavaThreadPool.enter(JavaThreadPool.java:91) ~[jurt-3.2.1.jar!/:na]
	at com.sun.star.lib.uno.bridges.java_remote.java_remote_bridge.sendRequest(java_remote_bridge.java:639) ~[jurt-3.2.1.jar!/:na]
	at com.sun.star.lib.uno.bridges.java_remote.ProxyFactory$Handler.request(ProxyFactory.java:151) ~[jurt-3.2.1.jar!/:na]
	at com.sun.star.lib.uno.bridges.java_remote.ProxyFactory$Handler.invoke(ProxyFactory.java:133) ~[jurt-3.2.1.jar!/:na]
	at com.sun.proxy.$Proxy74.storeToURL(Unknown Source) ~[na:na]
	at org.artofsolving.jodconverter.AbstractConversionTask.storeDocument(AbstractConversionTask.java:117) ~[jodconverter-core-1.0-SNAPSHOT.jar!/:na]
	at org.artofsolving.jodconverter.AbstractConversionTask.execute(AbstractConversionTask.java:55) ~[jodconverter-core-1.0-SNAPSHOT.jar!/:na]
	at org.artofsolving.jodconverter.office.PooledOfficeManager$2.run(PooledOfficeManager.java:75) ~[jodconverter-core-1.0-SNAPSHOT.jar!/:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_101]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_101]

**Comment by YountMan** [comment]
可能是目标文件 
```
http%3A%2F%2Fkelan.nat300.top%2Fprofile%2Favatar%2F2019%2F11%2F08%2F123456.doc
```
无法访问， 自己项目做了权限导致访问被拦截了， 我这边就是shiro 导致 文件访问时被拦截， 后来在路径访问中放过特定目录就可以了

**Comment by klboke** [comment]
由于该 issue 已长时间无新反馈（超过 1 年），为便于维护当前问题队列，先做关闭处理。\n\n如果问题在最新版本仍可复现，请基于最新版本重新提一个新 issue，并补充：\n1) 复现步骤\n2) 版本与部署方式\n3) 关键日志/报错截图\n\n我们会优先跟进。
